type Mutation {
  claimReward(id: ID!): ClaimedReward
}

type ClaimedReward {
  voucher: ClaimedVoucher!
  rewardSnapshot: RewardSnapshot!
}

type ClaimedVoucher {
  voucherDetailsTranslations: [TranslatedVoucherDetails!]!
  expirationDate: DateTime
}

type TranslatedVoucherDetails {
  languageCode: LanguageCode!
  voucherDetails: [VoucherDetails!]!
}

type RewardSnapshot {
  id: ID!
  redemptionForums: [RedemptionForum!]!
  rewardDetailsSnapshots: [TranslatedRewardDetailsSnapshot!]!
  partnerSnapshot: PartnerSnapshot!
  lastUpdatedAt: DateTime!
}

type TranslatedRewardDetailsSnapshot {
  languageCode: LanguageCode!
  categories: [String!]!
  shortDescription: String!
  longDescription: String
  lastUpdatedAt: DateTime!
}

type PartnerSnapshot {
  id: ID!
  partnerDetailsSnapshots: [TranslatedPartnerDetailsSnapshot!]!
  lastUpdatedAt: DateTime!
}

type TranslatedPartnerDetailsSnapshot {
  name: String!
  logoUrl: String!
  description: String!
  webAddressUrl: String
  webAddressText: String
  reasonForSupporting8by8: String
  lastUpdatedAt: DateTime!
}
