type Query {
  partner(id: ID!): Partner

  partners(
    filter: PartnerFilter
    orderBy: [PartnerOrderByCriteria!]
    take: Int = 50
  ): [Partner!]!

  partnerCount(filter: PartnerFilter): BigInt!

  location(id: ID!): Location

  locations(
    filter: LocationFilter
    orderBy: [LocationOrderByCriteria!]
    take: Int = 50
  ): [Location!]!

  locationCount(filter: LocationFilter): BigInt!

  reward(id: ID!): Reward

  rewards(
    filter: RewardFilter
    orderBy: [RewardOrderByCriteria!]
    take: Int = 50
  ): [Reward!]!

  rewardCount(filter: RewardFilter): BigInt!

  categories(languageTag: String!): [String!]!

  languages: [Language!]!
}
