type Query {
  partner(id: ID!): Partner

  partners(
    filter: PartnerFilter
    orderBy: [PartnerOrderByCriteria!]
    take: Int = 50
  ): [Partner!]!

  partnerCount(filter: PartnerFilter): Int!

  location(id: ID!): Location

  locations(
    filter: LocationFilter
    orderBy: [LocationOrderByCriteria!]
    take: Int = 50
  ): [Location!]!

  locationCount(filter: LocationFilter): Int!

  reward(id: ID!): Reward

  rewards(
    filter: RewardFilter
    orderBy: [RewardOrderByCriteria!]
    take: Int = 50
  ): [Reward!]!

  rewardCount(filter: RewardFilter): Int!

  categories(languageCode: LanguageCode!): [String!]!
}
