enum VoucherOwnership {
  SHARED
  INDIVIDUAL
}

enum RedemptionForum {
  ONLINE
  IN_STORE
}

type Reward {
  id: ID!
  voucherOwnership: VoucherOwnership!
  redemptionForums: [RedemptionForum!]!
  translatedDetails(languageTag: String!): RewardDetails!
  hasUsageOrQuantityLimit: Boolean!
  earliestFutureExpiryDate: DateTime
  partner: Partner!
}

type RewardDetails {
  categories: [String!]!
  shortDescription: String!
  longDescription: String
}

input RewardFilter @oneOf {
  id: IDFilter
  voucherOwnership: VoucherOwnershipFilter
  redemptionForums: RedemptionForumArrayFilter
  translatedDetails: TranslatedRewardDetailsFilter
  hasUsageOrQuantityLimit: BooleanFilter
  earliestFutureExpiryDate: DateTimeFilter
  partner: PartnerFilter
  _and: [RewardFilter!]
  _or: [RewardFilter!]
  _not: RewardFilter
}

input RedemptionForumArrayFilter @oneOf {
  _eq: [RedemptionForum!]
  _neq: [RedemptionForum!]
  _containsEl: RedemptionForum
  _containsArr: [RedemptionForum!]
  _containedBy: [RedemptionForum!]
  _overlaps: [RedemptionForum!]
}

input TranslatedRewardDetailsFilter {
  _languageTag: String!
  _filter: RewardDetailsFilter!
}

input RewardDetailsFilter @oneOf {
  categories: StringArrayFilter
  shortDescription: StringFilter
  longDescription: StringFilter
  _and: [RewardDetailsFilter!]
  _or: [RewardDetailsFilter!]
  _not: RewardDetailsFilter
}

input VoucherOwnershipFilter @oneOf {
  _eq: VoucherOwnership
  _neq: VoucherOwnership
}

input RewardOrderByCriteria @oneOf {
  id: SortOptions
  partner: PartnerOrderByCriteria
  translatedDetails: TranslatedRewardDetailsOrderByCriteria
}

input TranslatedRewardDetailsOrderByCriteria {
  _languageTag: String!
  _orderBy: RewardDetailsOrderByCriteria!
}

input RewardDetailsOrderByCriteria @oneOf {
  categories: SortOptions
  shortDescription: SortOptions
  longDescription: SortOptions
}
