enum VoucherType {
  MULTI_USER
  SINGLE_USER
}

enum RedemptionForum {
  ONLINE
  IN_STORE
}

type Reward {
  id: ID!
  voucherType: VoucherType!
  redemptionForums: [RedemptionForum!]!
  translatedDetails(languageCode: LanguageCode!): RewardDetails!
  hasUsageOrQuantityLimit: Boolean!
  earliestExpirationDate: DateTime
  partner: Partner!
}

type RewardDetails {
  categories: [String!]!
  shortDescription: String!
  longDescription: String
}

input RewardFilter @oneOf {
  id: IDFilter
  voucherType: VoucherTypeFilter
  redemptionForums: RedemptionForumArrayFilter
  translatedDetails: TranslatedRewardDetailsFilter
  hasUsageOrQuantityLimit: BooleanFilter
  earliestExpirationDate: DateTimeFilter
  partner: PartnerFilter
  _and: [RewardFilter!]
  _or: [RewardFilter!]
  _not: RewardFilter
}

input RedemptionForumArrayFilter @oneOf {
  _eq: [RedemptionForum!]
  _neq: [RedemptionForum!]
  _containsEl: RedemptionForum
  _containsArr: [RedemptionForum!]
  _containedBy: [RedemptionForum!]
  _overlaps: [RedemptionForum!]
}

input TranslatedRewardDetailsFilter {
  _languageCode: LanguageCode!
  _filter: RewardDetailsFilter!
}

input RewardDetailsFilter @oneOf {
  categories: StringArrayFilter
  shortDescription: StringFilter
  longDescription: StringFilter
  _and: [RewardDetailsFilter!]
  _or: [RewardDetailsFilter!]
  _not: RewardDetailsFilter
}

input VoucherTypeFilter @oneOf {
  _eq: VoucherType
  _neq: VoucherType
}

input RewardOrderByCriteria @oneOf {
  id: SortOrder
  partner: PartnerOrderByCriteria
  translatedDetails: TranslatedRewardDetailsOrderByCriteria
}

input TranslatedRewardDetailsOrderByCriteria {
  _languageCode: LanguageCode!
  _orderBy: RewardDetailsOrderByCriteria!
}

input RewardDetailsOrderByCriteria @oneOf {
  categories: SortOrder
  shortDescription: SortOrder
  longDescription: SortOrder
}
