enum DistanceUnits {
  KILOMETERS
  MILES
}

type Location {
  id: ID!
  coordinates: Coordinates!
  distance(from: InputCoordinates!, units: DistanceUnits!): Float!
  partner: Partner!
}

type Coordinates {
  latitude: Float!
  longitude: Float!
}

input InputCoordinates {
  latitude: Float!
  longitude: Float!
}

input LocationFilter @oneOf {
  id: IDFilter
  distance: DistanceFilter
  partner: PartnerFilter
  _and: [LocationFilter!]
  _or: [LocationFilter!]
  _not: LocationFilter
}

input DistanceFilter @oneOf {
  _within: DistanceWithinFilter
}

input DistanceWithinFilter {
  _radius: Float!
  _from: InputCoordinates!
  _units: DistanceUnits!
}

input LocationOrderByCriteria @oneOf {
  id: SortOrder
  distance: DistanceOrderByCriteria
  partner: PartnerOrderByCriteria
}

input DistanceOrderByCriteria {
  _from: InputCoordinates!
  _sortOrder: SortOrder!
}
type Mutation {
  retrieveVoucher(rewardID: ID!): VoucherWithRewardSnapshot
}
type Partner {
  id: ID!
  translatedDetails(languageCode: LanguageCode!): PartnerDetails!
  locations(
    filter: LocationFilter
    orderBy: [LocationOrderByCriteria!]
    take: Int
  ): [Location!]!
  locationsCount(filter: LocationFilter): Int!
  rewards(
    filter: RewardFilter
    orderBy: [RewardOrderByCriteria!]
    take: Int
  ): [Reward!]!
  rewardsCount(filter: RewardFilter): Int!
}

type PartnerDetails {
  name: String!
  logoUrl: String!
  description: String!
  webAddressUrl: String
  webAddressText: String
  reasonForSupporting8by8: String
}

input PartnerFilter @oneOf {
  id: IDFilter
  translatedDetails: TranslatedPartnerDetailsFilter
  rewardsCount: RewardsCountFilter
  locationsCount: LocationsCountFilter
  _and: [PartnerFilter!]
  _or: [PartnerFilter!]
  _not: PartnerFilter
}

input TranslatedPartnerDetailsFilter {
  _languageCode: LanguageCode!
  _filter: PartnerDetailsFilter!
}

input PartnerDetailsFilter @oneOf {
  name: StringFilter
  logoUrl: StringFilter
  description: StringFilter
  webAddressUrl: StringFilter
  webAddressText: StringFilter
  reasonForSupporting8by8: StringFilter
  _and: [PartnerDetailsFilter!]
  _or: [PartnerDetailsFilter!]
  _not: PartnerDetailsFilter
}

input LocationsCountFilter {
  _value: IntFilter!
  _filter: LocationFilter
}

input RewardsCountFilter {
  _value: IntFilter!
  _filter: RewardFilter
}

input PartnerOrderByCriteria @oneOf {
  id: SortOrder
  translatedDetails: TranslatedPartnerDetailsOrderByCriteria
}

input TranslatedPartnerDetailsOrderByCriteria {
  _languageCode: LanguageCode!
  _orderBy: PartnerDetailsOrderByCriteria!
}

input PartnerDetailsOrderByCriteria @oneOf {
  name: SortOrder
  logoUrl: SortOrder
  description: SortOrder
  webAddressUrl: SortOrder
  webAddressText: SortOrder
  reasonForSupporting8by8: SortOrder
}
type Query {
  partner(id: ID!): Partner

  partners(
    filter: PartnerFilter
    orderBy: [PartnerOrderByCriteria!]
    take: Int = 50
  ): [Partner!]!

  partnersCount(filter: PartnerFilter): Int!

  location(id: ID!): Location

  locations(
    filter: LocationFilter
    orderBy: [LocationOrderByCriteria!]
    take: Int = 50
  ): [Location!]!

  locationsCount(filter: LocationFilter): Int!

  reward(id: ID!): Reward

  rewards(
    filter: RewardFilter
    orderBy: [RewardOrderByCriteria!]
    take: Int = 50
  ): [Reward!]!

  rewardsCount(filter: RewardFilter): Int!

  categories(languageCode: LanguageCode!): [String!]!
}
enum VoucherOwnership {
  MULTI_USER
  SINGLE_USER
}

enum RedemptionForum {
  ONLINE
  IN_STORE
}

type Reward {
  id: ID!
  voucherOwnership: VoucherOwnership!
  redemptionForums: [RedemptionForum!]!
  translatedDetails(languageCode: LanguageCode!): RewardDetails!
  hasUsageOrQuantityLimit: Boolean!
  earliestExpirationDate: DateTime
  partner: Partner!
}

type RewardDetails {
  categories: [String!]!
  shortDescription: String!
  longDescription: String
}

input RewardFilter @oneOf {
  id: IDFilter
  voucherOwnership: VoucherOwnershipFilter
  redemptionForums: RedemptionForumArrayFilter
  translatedDetails: TranslatedRewardDetailsFilter
  hasUsageOrQuantityLimit: BooleanFilter
  earliestExpirationDate: DateTimeFilter
  partner: PartnerFilter
  _and: [RewardFilter!]
  _or: [RewardFilter!]
  _not: RewardFilter
}

input RedemptionForumArrayFilter @oneOf {
  _eq: [RedemptionForum!]
  _neq: [RedemptionForum!]
  _containsEl: RedemptionForum
  _containsArr: [RedemptionForum!]
  _containedBy: [RedemptionForum!]
  _overlaps: [RedemptionForum!]
}

input TranslatedRewardDetailsFilter {
  _languageCode: LanguageCode!
  _filter: RewardDetailsFilter!
}

input RewardDetailsFilter @oneOf {
  categories: StringArrayFilter
  shortDescription: StringFilter
  longDescription: StringFilter
  _and: [RewardDetailsFilter!]
  _or: [RewardDetailsFilter!]
  _not: RewardDetailsFilter
}

input VoucherOwnershipFilter @oneOf {
  _eq: VoucherOwnership
  _neq: VoucherOwnership
}

input RewardOrderByCriteria @oneOf {
  id: SortOrder
  partner: PartnerOrderByCriteria
  translatedDetails: TranslatedRewardDetailsOrderByCriteria
}

input TranslatedRewardDetailsOrderByCriteria {
  _languageCode: LanguageCode!
  _orderBy: RewardDetailsOrderByCriteria!
}

input RewardDetailsOrderByCriteria @oneOf {
  categories: SortOrder
  shortDescription: SortOrder
  longDescription: SortOrder
}
scalar DateTime
  @specifiedBy(url: "https://scalars.graphql.org/andimarek/date-time.html")

enum LanguageCode {
  EN
  ES
}

enum SortOrder {
  ASC
  DESC
}

input BooleanFilter @oneOf {
  _eq: Boolean
  _neq: Boolean
}

input DateTimeFilter @oneOf {
  _eq: DateTime
  _neq: DateTime
  _gt: DateTime
  _lt: DateTime
  _gte: DateTime
  _lte: DateTime
}

input IDFilter @oneOf {
  _eq: ID
  _neq: ID
  _gt: ID
  _lt: ID
  _gte: ID
  _lte: ID
  _containedBy: [ID!]
}

input IntFilter @oneOf {
  _eq: Int
  _neq: Int
  _gt: Int
  _lt: Int
  _gte: Int
  _lte: Int
}

input StringFilter @oneOf {
  _eq: CaseAwareStringFilterValue
  _neq: CaseAwareStringFilterValue
  _lt: String
  _gt: String
  _gte: String
  _lte: String
  _includes: CaseAwareStringFilterValue
  _like: CaseAwareStringFilterValue
  _containedBy: CaseAwareStringArrayFilterValue
}

input CaseAwareStringFilterValue {
  _value: String!
  _ignoreCase: Boolean = false
}

input CaseAwareStringArrayFilterValue {
  _value: [String!]!
  _ignoreCase: Boolean = false
}

input StringArrayFilter @oneOf {
  _eq: CaseAwareStringArrayFilterValue
  _neq: CaseAwareStringArrayFilterValue
  _containsEl: CaseAwareStringFilterValue
  _containsArr: CaseAwareStringArrayFilterValue
  _containedBy: CaseAwareStringArrayFilterValue
  _overlaps: CaseAwareStringArrayFilterValue
}
enum RedemptionMethod {
  CODE
  QR_CODE
  LINK
  MANUAL
}

type VoucherWithRewardSnapshot {
  voucher: Voucher!
  rewardSnapshot: RewardSnapshot!
}

type Voucher {
  translatedDetails(
    languageCodes: [LanguageCode!]
  ): [TranslatedVoucherDetails!]!
  expirationDate: DateTime
}

type TranslatedVoucherDetails {
  languageCode: LanguageCode!
  voucherDetails: [VoucherDetails!]!
}

interface VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
}

type CodeVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
  redemptionCode: String!
}

type QRCodeVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
  redemptionQRCode: String!
}

type LinkVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
  redemptionLinkUrl: String!
  redemptionLinkText: String
}

type ManualVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
}

type RewardSnapshot {
  id: ID!
  redemptionForums: [RedemptionForum!]!
  translatedDetailsSnapshots(
    languageCodes: [LanguageCode!]
  ): [TranslatedRewardDetailsSnapshot!]!
  partnerSnapshot: PartnerSnapshot!
  lastUpdatedAt: DateTime!
}

type TranslatedRewardDetailsSnapshot {
  languageCode: LanguageCode!
  categories: [String!]!
  shortDescription: String!
  longDescription: String
  lastUpdatedAt: DateTime!
}

type PartnerSnapshot {
  id: ID!
  translatedDetailsSnapshots(
    languageCodes: [LanguageCode!]
  ): [TranslatedPartnerDetailsSnapshot!]!
  lastUpdatedAt: DateTime!
}

type TranslatedPartnerDetailsSnapshot {
  languageCode: LanguageCode!
  name: String!
  logoUrl: String!
  description: String!
  webAddressUrl: String
  webAddressText: String
  reasonForSupporting8by8: String
  lastUpdatedAt: DateTime!
}
