scalar DateTime
  @specifiedBy(url: "https://scalars.graphql.org/andimarek/date-time.html")

scalar BigInt

enum SortOrder {
  ASC
  DESC
}

input SortOptions {
  _order: SortOrder!
  _nullsLast: Boolean = true
}

input BooleanFilter @oneOf {
  _eq: Boolean
  _neq: Boolean
}

input DateTimeFilter @oneOf {
  _eq: DateTime
  _neq: DateTime
  _gt: DateTime
  _lt: DateTime
  _gte: DateTime
  _lte: DateTime
}

input IDFilter @oneOf {
  _eq: ID
  _neq: ID
  _gt: ID
  _lt: ID
  _gte: ID
  _lte: ID
}

input BigIntFilter @oneOf {
  _eq: BigInt
  _neq: BigInt
  _gt: BigInt
  _lt: BigInt
  _gte: BigInt
  _lte: BigInt
}

# A regular-expression based filter has been intentionally omitted to avoid
# denial-of-service vulnerabilities.
input StringFilter @oneOf {
  _eq: CaseAwareStringFilterValue
  _neq: CaseAwareStringFilterValue
  _lt: String
  _gt: String
  _gte: String
  _lte: String
  _like: CaseAwareStringFilterValue
}

input CaseAwareStringFilterValue {
  _value: String!
  _ignoreCase: Boolean = false
}

input CaseAwareStringArrayFilterValue {
  _value: [String!]!
  _ignoreCase: Boolean = false
}

input StringArrayFilter @oneOf {
  _eq: CaseAwareStringArrayFilterValue
  _neq: CaseAwareStringArrayFilterValue
  _containsEl: CaseAwareStringFilterValue
  _containsArr: CaseAwareStringArrayFilterValue
  _containedBy: CaseAwareStringArrayFilterValue
  _overlaps: CaseAwareStringArrayFilterValue
}
