enum RedemptionMethod {
  CODE
  QR_CODE
  LINK
  MANUAL
}

type VoucherWithRewardSnapshot {
  voucher: Voucher!
  rewardSnapshot: RewardSnapshot!
}

type Voucher {
  translatedDetails(languageCodes: [String!]): [TranslatedVoucherDetails!]!
  expirationDate: DateTime
}

type TranslatedVoucherDetails {
  languageCode: String!
  voucherDetails: [VoucherDetails!]!
}

interface VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
}

type CodeVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
  redemptionCode: String!
}

type QRCodeVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
  redemptionQRCode: String!
}

type LinkVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
  redemptionLinkUrl: String!
  redemptionLinkText: String
}

type ManualVoucherDetails implements VoucherDetails {
  redemptionMethod: RedemptionMethod!
  instructions: String!
}

type RewardSnapshot {
  id: ID!
  redemptionForums: [RedemptionForum!]!
  translatedDetailsSnapshots(
    languageCodes: [String!]
  ): [TranslatedRewardDetailsSnapshot!]!
  partnerSnapshot: PartnerSnapshot!
  lastUpdatedAt: DateTime!
}

type TranslatedRewardDetailsSnapshot {
  languageCode: String!
  categories: [String!]!
  shortDescription: String!
  longDescription: String
  lastUpdatedAt: DateTime!
}

type PartnerSnapshot {
  id: ID!
  translatedDetailsSnapshots(
    languageCodes: [String!]
  ): [TranslatedPartnerDetailsSnapshot!]!
  lastUpdatedAt: DateTime!
}

type TranslatedPartnerDetailsSnapshot {
  languageCode: String!
  name: String!
  logoUrl: String!
  description: String!
  webAddressUrl: String
  webAddressText: String
  reasonForSupporting8by8: String
  lastUpdatedAt: DateTime!
}
