enum RewardType {
  PUBLIC
  CLAIMABLE
}

enum RedemptionForum {
  ONLINE
  IN_STORE
}

interface IReward {
  id: ID!
  rewardType: RewardType!
  redemptionForums: [RedemptionForum!]!
  rewardDetails(languageCode: LanguageCode!): RewardDetails!
  partner: Partner!
}

union Reward = PublicReward | ClaimableReward

type PublicReward implements IReward {
  id: ID!
  rewardType: RewardType!
  redemptionForums: [RedemptionForum!]!
  partner: Partner!
  rewardDetails(languageCode: LanguageCode!): RewardDetails!
  publicVoucher: PublicVoucher!
}

type ClaimableReward implements IReward {
  id: ID!
  rewardType: RewardType!
  redemptionForums: [RedemptionForum!]!
  partner: Partner!
  rewardDetails(languageCode: LanguageCode!): RewardDetails!
  earliestExpirationDate: DateTime
}

type RewardDetails {
  categories: [String!]!
  shortDescription: String!
  longDescription: String
}

input RewardFilter @oneOf {
  id: IDFilter
  redemptionForums: RedemptionForumArrayFilter
  rewardDetails: TranslatedRewardDetailsFilter
  partner: PartnerFilter
  rewardType: RewardTypeFilter
  publicVoucher: TranslatedPublicVoucherFilter
  earliestExpirationDate: DateTimeFilter
  _and: [RewardFilter!]
  _or: [RewardFilter!]
  _not: RewardFilter
}

input RedemptionForumArrayFilter @oneOf {
  _eq: [RedemptionForum!]
  _neq: [RedemptionForum!]
  _containsEl: RedemptionForum
  _containsArr: [RedemptionForum!]
  _containedBy: [RedemptionForum!]
  _overlaps: [RedemptionForum!]
}

input TranslatedRewardDetailsFilter {
  _languageCode: LanguageCode!
  _filter: RewardDetailsFilter!
}

input RewardDetailsFilter @oneOf {
  shortDescription: StringFilter
  longDescription: StringFilter
  categories: StringArrayFilter
  _and: [RewardDetailsFilter!]
  _or: [RewardDetailsFilter!]
  _not: RewardDetailsFilter
}

input RewardTypeFilter @oneOf {
  _eq: RewardType
  _neq: RewardType
}

input TranslatedPublicVoucherFilter {
  _languageCode: LanguageCode!
  _filter: PublicVoucherFilter!
}

input PublicVoucherFilter @oneOf {
  hasLimitedTotalUses: BooleanFilter
  expirationDate: DateTimeFilter
}

input RewardOrderByCriteria @oneOf {
  id: SortOrder
  partner: PartnerOrderByCriteria
  rewardDetails: TranslatedRewardDetailsOrderByCriteria
}

input TranslatedRewardDetailsOrderByCriteria {
  _languageCode: LanguageCode!
  _orderBy: RewardDetailsOrderByCriteria!
}

input RewardDetailsOrderByCriteria @oneOf {
  categories: SortOrder
  shortDescription: SortOrder
  longDescription: SortOrder
}
