scalar DateTime

enum LanguageCode {
  EN
  ES
}

enum SortOrder {
  ASC
  DESC
}

input BooleanFilter @oneOf {
  _eq: Boolean
  _neq: Boolean
}

input DateTimeFilter @oneOf {
  _eq: DateTime
  _neq: DateTime
  _gt: DateTime
  _lt: DateTime
  _gte: DateTime
  _lte: DateTime
}

input IDFilter {
  _eq: ID
  _neq: ID
  _gt: ID
  _lt: ID
  _gte: ID
  _lte: ID
  _containedBy: [ID!]
}

input IntFilter {
  _eq: Int
  _neq: Int
  _gt: Int
  _lt: Int
  _gte: Int
  _lte: Int
}

input StringFilter {
  _eq: String
  _neq: String
  _lt: String
  _gt: String
  _gte: String
  _lte: String
  _like: LikeOperatorValue
  _includes: String
  _includedBy: String
  _containedBy: [String!]
}

input LikeOperatorValue {
  _value: String!
  _ignoreCase: Boolean = false
}

input StringArrayFilter {
  _eq: [String!]
  _neq: [String!]
  _gt: [String!]
  _lt: [String!]
  _gte: [String!]
  _lte: [String!]
  _containsEl: String
  _containsArr: [String!]
  _containedBy: [String!]
  _overlaps: [String!]
}
