scalar DateTime

enum LanguageCode {
  EN
  ES
}

enum SortOrder {
  ASC
  DESC
}

input BooleanFilter @oneOf {
  _eq: Boolean
  _neq: Boolean
}

input DateTimeFilter @oneOf {
  _eq: DateTime
  _neq: DateTime
  _gt: DateTime
  _lt: DateTime
  _gte: DateTime
  _lte: DateTime
}

input IDFilter @oneOf {
  _eq: ID
  _neq: ID
  _gt: ID
  _lt: ID
  _gte: ID
  _lte: ID
  _containedBy: [ID!]
}

input IntFilter @oneOf {
  _eq: Int
  _neq: Int
  _gt: Int
  _lt: Int
  _gte: Int
  _lte: Int
}

input StringFilter @oneOf {
  _eq: CaseAwareStringFilterValue
  _neq: CaseAwareStringFilterValue
  _lt: String
  _gt: String
  _gte: String
  _lte: String
  _includes: CaseAwareStringFilterValue
  _like: CaseAwareStringFilterValue
  _containedBy: CaseAwareStringArrayFilterValue
}

input CaseAwareStringFilterValue {
  _value: String!
  _ignoreCase: Boolean = false
}

input CaseAwareStringArrayFilterValue {
  _value: [String!]!
  _ignoreCase: Boolean = false
}

input StringArrayFilter @oneOf {
  _eq: CaseAwareStringArrayFilterValue
  _neq: CaseAwareStringArrayFilterValue
  _containsEl: CaseAwareStringFilterValue
  _containsArr: CaseAwareStringArrayFilterValue
  _containedBy: CaseAwareStringArrayFilterValue
  _overlaps: CaseAwareStringArrayFilterValue
}
